### ISSUE TITLE
Error looking for the Splash Screen...

### ISSUE THREAD

**Issue by spycolyf** [KitwareMedical/SlicerQReads#42] opened 2021-03-01 20:22 UTC
Hello JC, Liqin did the new build and iy seems SlicerQREADS is still looking for the splash screen. And crashes. Is this fixable? Maybe we need to fake it out.

**Comment by jcfr** [comment] 2021-03-01 20:31
Closing. Duplicate of https://github.com/KitwareMedical/SlicerQReads/issues/43

**Closed as completed by jcfr** 2021-03-01 20:31 UTC
Labels: bug
